name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main
      - trivy

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ci-html:1.0.1 .

  scan-trivy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "ci-html:1.0.1"
          format: "table"
          exit-code: 1
          severity: "CRITICAL,HIGH"

  deploy:
    needs: scan-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Final Deploy
        run: echo "Déploiement réussi après scan !"
