name: CI-CD Docker Pipeline Stable

on:
  push:
    branches:
      - main
      - trivy

jobs:
  ci-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker Image Locally
        run: docker build -t html5up-image:latest .

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: "html5up-image:latest"
          format: "table"
          exit-code: 0
          severity: "CRITICAL,HIGH"

      - name: Simulation Deploy
        run: echo "L'image a été buildée et scannée avec succès. Prête pour la production !"
